replicaCount: 1

image:
  repository: ghcr.io/piscoroma/inventory-service
  tag: latest
  pullPolicy: Always
  
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3010

env:
  SHUTDOWN_TIMEOUT: 25000
  LOG_LEVEL: info

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 10
    
serviceAccount:
  create: true
  name: ""

