{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "inventory-service.fullname" . }}-seed
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: seed
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "2"

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: {{ include "inventory-service.fullname" . }}
        app.kubernetes.io/component: seed

    spec:
      restartPolicy: Never

      containers:
        - name: inventory-seed
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - npm
            - run
            - seed

          envFrom:
            - configMapRef:
                name: {{ include "inventory-service.fullname" . }}-config
            - secretRef:
                name: inventory-service-db-secret
{{- end }}
