apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-service.fullname" . }}
  labels:
    app: {{ include "inventory-service.name" . }}
    {{- include "inventory-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: service
      port: {{ .Values.service.port }}
      targetPort: service
  selector:
    {{- include "inventory-service.selectorLabels" . | nindent 4 }}

