inventory-service:
  image:
    tag: sha-d6ae4f1
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: test
    NATS_URL: "nats://nats.order-event-platform:4222"
    MONGO_HOST: mongo.order-event-platform
  
auth-service:
  image:
    tag: sha-d6ae4f1
    pullPolicy: IfNotPresent
  env:
    NODE_ENV: test
    MONGO_HOST: mongo.order-event-platform
      
jwt:
  publicKeyConfigMap:
    enabled: false

ingress:
  enabled: true
  className: traefik
  host: "api.order-event-platform"
  annotations: {}
  tls:
    enabled: false
    secretName: ""
  paths:
    auth: /auth
    inventory: /inventory
    
serviceMonitor:
  enabled: true

external-services:
  enabled: false
    
test-dependencies:
  enabled: true
