apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    # deployment knows which are its pods through the labels
    matchLabels:
      {{- include "auth-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # labels added to the pods when they are created 
      labels:
        {{- include "auth-service.selectorLabels" . | nindent 8 }}
      annotations:
        # force the rollout when configMap changes, even if image tag is not changed
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: service
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "auth-service.fullname" . }}-config
            - secretRef:
                name: auth-service-db-secrets
          env:
            - name: JWT_PRIVATE_KEY_PATH
              value: {{ .Values.jwt.mountPath }}/private.pem
            - name: JWT_PUBLIC_KEY_PATH
              value: {{ .Values.jwt.mountPath }}/public.pem
          volumeMounts:
            - name: jwt-keys
              mountPath: {{ .Values.jwt.mountPath }}
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: jwt-keys
          secret:
            secretName: auth-service-jwt-secrets
            items:
              - key: private.pem
                path: private.pem
              - key: public.pem
                path: public.pem

