{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-event-platform
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - order-event-platform

  selector:
    matchLabels:
      app.kubernetes.io/instance: order-event-platform

  endpoints:
    - port: service
      path: /metrics
      interval: 30s
{{- end }}
