apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: mongodb
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
subsets:
  - addresses:
      - ip: {{ .Values.mongo.host }}
    ports:
      - name: mongodb
        port: {{ .Values.mongo.port }}
