{{- if .Values.jwt.publicKeyConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-public-key
data:
  public.pem: |
{{ .Values.jwt.publicKeyConfigMap.publicKey | indent 4 }}
{{- end }}
