#inventory-service:
#  image:
#    repository: inventory-service
#    tag: test
#    pullPolicy: Never

#  env:
#    LOG_LEVEL: debug
  
#auth-service:
#  image:
#    repository: auth-service
#    tag: test
#    pullPolicy: Never

#  env:
#    LOG_LEVEL: debug

jwt:
  publicKeyConfigMap:
    enabled: true
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv3FnduktqWRsra4XQH5eFc+7ahXS
      h2oMXSLC4y06xvKZZ+UKA2nQ0qXj+6uDl9vqy9Blrbse16SLTGnoxpJwdQ==
      -----END PUBLIC KEY-----
      
ingress:
  enabled: true
  host: api.order-event-platform
  tls:
    enabled: true
    secretName: order-event-platform-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

external-services:
  enabled: true
  mongo:
    host: 192.168.1.175
    port: 27017
  nats:
    host: 192.168.1.175
    clientPort: 4222
    monitorPort: 8222
    
test-dependencies:
  enabled: false
