inventory-service:

  image:
    repository: inventory-service
    tag: latest
    pullPolicy: Never

  ingressRoute:
    enabled: false

  env:
    NODE_ENV: test
    NATS_URL: "nats://nats.order-event-platform:4222"
    MONGO_HOST: mongo.order-event-platform
    
  secretName: inventory-service-secrets

external-services:
  enabled: false
  
test-dependencies:
  enabled: true
