inventory-service:
  image:
    repository: inventory-service
    pullPolicy: Never
  
auth-service:
  image:
    repository: auth-service
    pullPolicy: Never

ingress: 
  enabled: true
  host: api.order-event-platform
