apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: mongodb
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mongo
  labels:
    kubernetes.io/service-name: mongo
addressType: IPv4
ports:
  - name: mongodb
    protocol: TCP
    port: {{ .Values.mongo.port }}
endpoints:
  - addresses:
      - {{ .Values.mongo.host }}
