apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  ports:
    - name: client
      port: {{ .Values.nats.clientPort }}
      targetPort: {{ .Values.nats.clientPort }}

    - name: monitor
      port: {{ .Values.nats.monitorPort }}
      targetPort: {{ .Values.nats.monitorPort }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nats
  labels:
    kubernetes.io/service-name: nats
addressType: IPv4
ports:
  - name: client
    protocol: TCP
    port: {{ .Values.nats.clientPort }}
  - name: monitor
    protocol: TCP
    port: {{ .Values.nats.monitorPort }}
endpoints:
  - addresses:
      - {{ .Values.nats.host }}
