apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inventory-service.fullname" . }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    # deployment knows which are its pods through the labels
    matchLabels:
      {{- include "inventory-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # labels added to the pods when they are created 
      labels:
        {{- include "inventory-service.selectorLabels" . | nindent 8 }}
      annotations:
        # force the rollout when configMap changes, even if image tag is not changed
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inventory-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: service
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "inventory-service.fullname"-config . }}
            {{- if .Values.secretEnv }}
            - secretRef:
                name: {{ include "inventory-service.fullname"-secret . }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

