name: CI/CD

on:
#  push:
#    branches:
#      - main

  workflow_dispatch:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm ci


      - name: Run lint
        run: npm run lint
        
        
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm ci


      - name: Run tests
        run: npm test
        
        
  build:

    needs:
      - lint
      - test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Build inventory-service image
        run: |
          docker build \
            -f docker/Dockerfile \
            --build-arg SERVICE_NAME=inventory-service \
            --build-arg SERVICE_PORT=3010 \
            -t inventory-service:test \
            .


      - name: Build auth-service image
        run: |
          docker build \
            -f docker/Dockerfile \
            --build-arg SERVICE_NAME=auth-service \
            --build-arg SERVICE_PORT=3011 \
            -t auth-service:test \
            .
            
            
            
